# -*- coding: utf-8 -*-
"""script.ipnyb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LLAV1X5Rs41iRIW-4u2Nj-YwbQWv9v3C
"""

!pip install neattext

import pandas as pd
import numpy as np
import seaborn as sns
import neattext.functions as nfx
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df = pd.read_csv("/content/emotion_dataset_raw.csv")

df.head()

# Value Counts
df['Emotion'].value_counts()

# Plot
sns.countplot(x='Emotion',data=df)

# Data Cleaning
dir(nfx)

# User handles
df['Clean_Text'] = df['Text'].apply(nfx.remove_userhandles)

# Stopwords
df['Clean_Text'] = df['Clean_Text'].apply(nfx.remove_stopwords)

df

# Features & Labels
Xfeatures = df['Clean_Text']
ylabels = df['Emotion']

#  Split Data
x_train,x_test,y_train,y_test = train_test_split(Xfeatures,ylabels,test_size=0.3,random_state=42)

# Build Pipeline
from sklearn.pipeline import Pipeline

# LogisticRegression Pipeline
pipe_lr = Pipeline(steps=[('cv',CountVectorizer()),('lr',LogisticRegression())])

# Train and Fit Data
pipe_lr.fit(x_train,y_train)

pipe_lr

# Check Accuracy
pipe_lr.score(x_test,y_test)

# Make A Prediction
ex1 = "This book was so interesting it made me happy"

pipe_lr.predict([ex1])

# Prediction Prob
pipe_lr.predict_proba([ex1])

# To Know the classes
pipe_lr.classes_

# Save Model & Pipeline
import joblib
pipeline_file = open("emotion_classifier_pipe_lr_03_june_2021.pkl","wb")
joblib.dump(pipe_lr,pipeline_file)
pipeline_file.close()